export const config = {
  settings: {
    wsol_pc_mint: 'So11111111111111111111111111111111111111112',
    inspect_url: 'https://gmgn.ai/sol/token/',
    inspect_name: '👽 Open GMGN',
    inspect_url_wallet: 'https://gmgn.ai/sol/address/',
    show_max_duplicates: 5,
    show_duplicate_min_holders: 3, // Minimum wallets that need to hold the token before showing it as duplicate
  },
  db: {
    db_name_tracker_transfers: 'src/db/holdings.db', // Sqlite Database location
  },
  // wallets: [
  //   {
  //     name: "Wallet0",
  //     address: "GchNdch4w3L9SoRmHvD6G4zNYrNdQgpScLVF7DojMK4s",
  //     emoji: "👽",
  //     tags: [],
  //   },
  //   {
  //     name: "Wallet1",
  //     address: "KEN7s6mHAFpqmvppk7L9VaJW3htu3jz6z3dDjiaWdYT",
  //     emoji: "🀄️",
  //     tags: [],
  //   },
  //   {
  //     name: "Frank",
  //     address: "CRVidEDtEUTYZisCxBZkpELzhQc9eauMLR3FWg74tReL",
  //     emoji: "😂",
  //     tags: [],
  //   },
  //   {
  //     name: "Profit",
  //     address: "G5nxEXuFMfV74DSnsrSatqCW32F34XUnBeq3PfDS7w5E",
  //     emoji: "💰",
  //     tags: [],
  //   },
  //   {
  //     name: "DigBen",
  //     address: "CKddnqDi9hTPDr3ovyLfseJ17ddr553u1MXKV9VpGiJ9",
  //     emoji: "🚀",
  //     tags: [],
  //   },
  // ],
  wallets: [
    {
      name: '$5m_Profit_Whale_30_Days',
      address: 'KANYEsXAntLxYUE6GtPJ5CahFGpEbaSbd5xhNFYbvq3',
      emoji: '👽',
      tags: [],
    },
    {
      name: '$kanyefnf.sol',
      address: 'KANYEsXAntLxYUE6GtPJ5CahFGpEbaSbd5xhNFYbvq3',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'NGMI_sniped_indexsy',
      address: '8DmxdnkWivweA4EpmUMdfbjHtdzQ8anrx13hz1Pm27uh',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Biee',
      address: 'BieeZkdnBAgNYknzo3RH2vku7FcPkFZMZmRJANh2TpW',
      emoji: '👽',
      tags: [],
    },
    {
      name: '0xsun.sol',
      address: 'HUpPyLU8KWisCAr3mzWy2FKT6uuxQ2qGgJQxyTpDoes5',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Libra_T7',
      address: 'hJRWEXNPGcjvYyPqttHC4Fba3ZeNDBFkb15E32EwhAR',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Libra_T1',
      address: '713uW1orSNGqyeChyW3EMhqa9rTSHqjP9tFWrjqp4v26',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'WORTHZERO_BIG_GUN_1',
      address: '1pto5y4du2BNBCGonJun1b3t5sSRq8fQwUvShGTvgru',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'WORTHZERO_BIG_GUN_2',
      address: '6ggPoVSC7mi867dnqxMMS3TeiPwnR8J8nxxogYczc2Px',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'WORTHZERO_BIG_GUN_3',
      address: 'uTT8Zm99N9Eovn3Lrz2vKpat2uNSAszoxHW4joPZ4st',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'WORTHZERO_BIG_GUN_4',
      address: '9EVQtdWf2TBV4FhGLv1V2wQepq1j9jaKc4xCbdUE2NZA',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'WORTHZERO_BIG_GUN_5',
      address: 'DEUF3q6fynk3VCbPWeRPYHxTSgGWCjkkprJKcY2kU1bt',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Jelly_#4_1',
      address: '5BjQLkjoKic2PLv52iszv3u9VenvDN3PM9s1tnL37Eqo',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Jelly_#4_2',
      address: '4t2bx5bqSL22xoNAh12eQNSfRbTt9AymK471TgchBst8',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Pill_Insiders_1',
      address: '4kX6v9H3dUZ3iA2REcGGvSNAWoSwdCjvLaSKR8kPCjmZ',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Pill_Insiders_2',
      address: '96sErVjEN7LNJ6Uvj63bdRWZxNuBngj56fnT9biHLKBf',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Pill_Insiders_3',
      address: 'EEytiKSTRmD54bkNHQD3fSLyMmSDpdwNpoR4jLFxUfFJ',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'ERIC_Trump_Whale',
      address: '71CPXu3TvH3iUKaY1bNkAAow24k6tjH473SsKprQBABC',
      emoji: '👽',
      tags: [],
    },
    {
      name: '$1m_Profit_Whale_30_Days_1',
      address: '4PdhGpHFWjt5vpWuZgpjR3PbHxtwpszLPHG1vNNEJTB7',
      emoji: '👽',
      tags: [],
    },
    {
      name: '$1m_Profit_Whale_30_Days_2',
      address: 'DfMxre4cKmvogbLrPigxmibVTTQDuzjdXojWzjCXXhzj',
      emoji: '👽',
      tags: [],
    },
    {
      name: '$1m_Profit_Whale_30_Days_3',
      address: 'K27kZNq1P9a7A9HMSrkcwzLD7maN2S4VjhZW1ZSAvaG',
      emoji: '👽',
      tags: [],
    },
    {
      name: '$ASYM_Whale_1',
      address: 'BrNoqdHUCcv9yTncnZeSjSov8kqhpmzv1nAiPbq1M95H',
      emoji: '👽',
      tags: [],
    },
    {
      name: '$ASYM_Whale_2',
      address: 'ATmKENkRrL1JQQnoUNAQvkiwgjiHKUkzyncxTGxyzQL1',
      emoji: '👽',
      tags: [],
    },
    {
      name: '$ASYM_Whale_3',
      address: 'RH6epK9UW5vA5rm23FcLi4rPuTJjwya6UQJeG1tigv3',
      emoji: '👽',
      tags: [],
    },
    {
      name: '$ASYM_Dev_1',
      address: 'TEMPaMeCRFAS9EKF53Jd6KpHxgL47uWLcpFArU1Fanq',
      emoji: '👽',
      tags: [],
    },
    {
      name: '$ASYM_Dev_2',
      address: '5MNizMzFryXZC5JPxdH9ugfgmJcyLBKxENiGRAZygBRS',
      emoji: '👽',
      tags: [],
    },
    {
      name: '$ASYM_Dev_3',
      address: 'B1HkS94ad5WMDP9KwhXVZVwSCuxV9LbVdkbhhgVwLmhq',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Chillguy_H9_1',
      address: '3AWDTDGZiW8joyfA52LKL7GUWLoKBCBUBLUE5JoWgBCu',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Chillguy_H9_1',
      address: 'kLw1WqvZqxP4hGyB83zMSDXqJbbKtcSYCLtGfYadXM1',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Chillguy_H9_1',
      address: 'JBzZqpknhahgfKQXhoE1UcHtRGMDoSAWrWF23j2je1wx',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Chillguy_T7_1',
      address: 'DFTvt9LdKLKVuLjXxyFsP2W7WQwDnawgpqUz5f6gkfxj',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Chillguy_T7_2',
      address: 'AVahywMVNRYzdgWrufSWrtdGXAeNEvfpJFxhVFK516mT',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Limbo_T3_1',
      address: 'DZXhgTPuvjrQuLMC1NRoNzvTSsQ4R5xdQGx8CUowktND',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Limbo_T3_2',
      address: 'DZXhgTPuvjrQuLMC1NRoNzvTSsQ4R5xdQGx8CUowktND',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Limbo_T3_3',
      address: '7zCnMseaC7V91PYRP7UXepz9v8CG2rm3k3vgGruRDnx1',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Limbo_T3_4',
      address: '8y9ox5P36vD6vhxAbX3s8zSVA2XneEdrqvFBvkwH7ajh',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'FATHA_Insider_T3_1',
      address: '5ZAMqhST6QXQ2Sv5RYDnt4K19RQ9gWjPq2ycHNvdJrkA',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'FATHA_Insider_T3_2',
      address: 'AwxF8toUqbjhZaZrEFx7PvoRrCEpxP8JdKo7e2WoDJt8',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'FATHA_Insider_T3_3',
      address: 'BRJGzKD7P6T6Z1ToA2iHzkfW4UgYJrCjVLhD9kZoCQAQ',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'PURE_Insider_1',
      address: '4ADFwrmsrdSVUx8cp7mVtcynvM3hFcdkBZk4vi83KnrA',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'PURE_Insider_1',
      address: '5XWC8J3tEwvWN8AFv1eBBS1MCTdkf3WuHCi3TU5eAEs4',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'PURE_Insider_1',
      address: 'ASWfCnDhme9LDFG2JqKtqqayjd4NKxusxxVRQweoyF8H',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'PURE_Insider_1',
      address: 'DA99QFqcpazy1d6hCCrzQfxdY2dz2nctjrrmm1BUpACN',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Shar_Insider',
      address: 'DeqbwVpX4Zapiz2rEX8YbYW7gwwbhB8bNDPXsAkJsNTD',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'Greed_Trader#8',
      address: 'CU35ZDB4JptaBVQWiq1gZsR8kso6dz1bQj8uR3xGn2kK',
      emoji: '👽',
      tags: [],
    },
    {
      name: 'test',
      address: 'EgDta9Sw1ikuzd11NimM12YwPEqee1T98CnJzmvMfZwV',
      emoji: '👽',
      tags: [],
    },
  ],
}
